config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  get '/about' => 'homes#about'
  resources :users
  resources :books

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true , length: {maximum: 200 }
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy
  
  has_one_attached :profile_image
  
  validates :name, presence: true, uniqueness: true, length: {minimum: 2 , maximum: 20}
  validates :introduction, length: {maximum: 50}
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/my-icon.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      profile_image.variant(resize_to_limit: [width, height]).processed
    
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    users_path
  end
  
  
  
  protected
  
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book = Book.new
    @books = Book.all
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:id] = "You have created book successfully."
      redirect_to book_path(@book.id)
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end
  
  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      flash[:notice] = "You have deleted book successfully."
      redirect_to books_path
    end
  end
  
  private
  
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = current_user
    @book = Book.new
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-11 col-sm-10 col-md-8 col-xl-6 mx-auto">
      <h1>Editing Book</h1>
      <%= form_with model: @book , method: :patch do |f| %>
        <div class="form-group">
          <%= f.label :title %><br>
          <%= f.text_field :title , class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :body, "Opinion" %><br>
          <%= f.text_area :body , class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update Book", class:"btn btn-success" %>
        </div>
      <% end %>
      <%= link_to "Show", book_path(@book.id) %> | <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <%= render "layouts/user_info" , user: current_user , book: @book %>
    <div class="col-8 offset-1">
      <h1>Books</h1>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user.id) do %>
                  <%= image_tag book.user.get_profile_image(100,100) %>
                <% end %>  
              </td>
              <td><%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
    <div class="row">
        <%= render "layouts/user_info" , user: @book.user , book: Book.new %>
        <div class="col-8 offset-1">
            <h1>Book detail</h1>
            <table class="table">
                <tbody>
                    <%# @books.each do |book| %>
                        <tr>
                            <td>
                                <%= link_to  user_path(@book.user.id) do %>
                                    <%= image_tag  @book.user.get_profile_image(100,100) %><br>
                                    <%= @book.user.name %>
                                    <!--<p>たい</p>-->
                                <% end %>
                            </td>
                            <td>
                                <%= link_to  book_path(@book.id) do %>
                                    <%= @book.title %>
                                <% end %>
                            </td>
                            <td>
                                <%= @book.body %>
                            </td>
                            <td>
                                <%= link_to "Edit" , edit_book_path(@book.id) ,class:"btn btn-success" %>
                            </td>
                            <td>
                                <%= link_to "Destroy", book_path(@book.id) , method: :delete , "data-confirm" => "本当に削除しますか" ,class:"btn btn-danger" %>
                            </td>
                        </tr>
                    <%# end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <div class="col-10 col-md-8 col-xl-6 mx-auto">
      <h1>Welcome to <i class="fas fa-book"></i><strong>Bookers!</strong></h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
    <div class="row">
        <div class="mx-auto col-11 col-sm-10 col-md-8 col-xl-6">
            <h1>welcome to <i class="fas fa-book"></i><strong>Bookers!!</strong></h1>
            <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
            <p>you can share and exchange your opinions , inpressions , and emotions</p>
            <p>about various books!</p>
            <div class="btn-wrapper col-10 mx-auto">
                <%= link_to "Log in", new_user_session_path , class:"btn btn-block btn-primary" %>
                <%= link_to "Sign up", new_user_registration_path , class:"btn btn-block btn-success" %>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <h1><%= pluralize(obj.errors.count, "error") %>prohibited this obj from being saved:</h1>
  <ul>
    <% obj.errors.full_messages.each do |message| %>
      <li>
        <%= message %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_user_info.html.erb
    <div class="col-3">
      <h1>User info</h1>
      <%= image_tag user.get_profile_image(200,200) %>
      <table class="table">
        <tbody>
          <tr>
            <th>name</th>
            <th><%= user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
          </tr>
        </tbody>
      </table>
      <div class="mt-5">
        <%= link_to edit_user_path(user.id),class:"btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-user-cog"></i>
        <% end %>
      </div>
      <h1>New book</h1>
      <div class="form-group">
        <%= form_with model: book do |f| %>
          <%= f.label :title %><br>
          <%= f.text_field :title ,class:"form-control" %><br>
          <%= f.label :body, "Opinion" %><br>
          <%= f.text_area :body, class:"form-control" %><br>
          <%= f.submit "Create Book" ,class:"btn btn-success" %>
        <% end %>
      </div>
      
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to "Bookers" ,root_path ,class:"navbar-brand" %>
          <ul class="navbar-nav">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to user_path(current_user.id) ,class:"nav-link text-light" do %>
                  <i class="fas fa-home"></i> Home
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to  users_path , class:"nav-link text-light" do %>
                  <i class="fas fa-users"></i> Users
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to  books_path, class:"nav-link text-light" do %>
                  <i class="fas fa-book-open"></i> Books
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to  destroy_user_session_path,method: :delete, class:"nav-link text-light" do %>
                  <i class="fas fa-sign-out-alt"></i> Log out
                <% end %>
              </li>
              
            <% else %>
            
              <li class="nav-item">
                <%= link_to root_path ,class:"nav-link text-light" do %>
                  <i class="fas fa-home"></i> Home
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to  about_path , class:"nav-link text-light" do %>
                  <i class="fas fa-link"></i> About
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to  new_user_registration_path, class:"nav-link text-light" do %>
                  <i class="fas fa-user-plus"></i> Sign up
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to  new_user_session_path, class:"nav-link text-light" do %>
                  <i class="fas fa-sign-in-alt"></i> Log in
                <% end %>
              </li>
            <% end %>
          </ul>
      </nav>
    </header>
    <%= flash[:notice] %>
    <p id="notice"></p>
    <%= yield %>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <p class="mx-auto">CopyRight Infratop.inc</p>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-11 col-sm-10 col-md-8 col-xl-6 mx-auto">
      <h1>User info</h1>
      <%= render "layouts/errors" , obj: @user %>
      <%= form_with model: @user do |f| %>
        <div class="form-group">
          <%= f.label :name %><br>
          <%= f.text_field :name, autocomplete: "name", class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :profile_image , "Image" %><br>
          <%= f.file_field :profile_image, accept: "image/*" %>
        </div>
        <div class="form-group">
          <%= f.label :introduction %>
          <%= f.text_area :introduction, autocomplete: "introduction", class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update User", class:"btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <%= render "layouts/user_info" , user: @user , book: @book %>
    <div class="col-8 offset-md-1">
      <h1>Users</h1>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <th><%= image_tag user.get_profile_image(100,100) %></th>
              <th><%= user.name %></th>
              <th><%= link_to "Show" , user_path(user.id) %></th>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <%= render "layouts/user_info" , user: @user , book: Book.new %>
    <div class="col-8 offset-1">
      <h1>Books</h1>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user.id) do %>
                  <%= image_tag book.user.get_profile_image(100,100) %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td>
                <%= book.body %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>